### ISSUE TITLE
Meilisearch Index size limit

### ISSUE THREAD

**Issue by b0xtch** [tryffel/virtualpaper#1]
*meilisearch* has a known limit of 200 indices, I see that you are just creating an index for every user. How would you go about achieving the same functionality to support more than 200 users? 

[Index Limit Docs](https://docs.meilisearch.com/reference/features/known_limitations.html#number-of-indexes)

**Comment by tryffel** [comment]
Yes I think it's ok to put all documents in one index. The idea behind index per user was to allow per-user configuration (synonyms being one), which can be set for each index.
