### ISSUE TITLE
Username must be lowercase

### ISSUE THREAD

**Issue by Opt6** [tryffel/virtualpaper#2]
I've set this up on unRAID and noticed that if I use the command line to create a user with any uppercase characters the GUI returns "Unauthorized" on commit eb6d8b0.

**Comment by tryffel** [comment]
Fixed this with fd599fb. I decided that from now on, usernames will be lower cased in database and this will be automatic when creating new users. The application expects them to be lowercase. If you have existing usernames in your db, you can manually lowercase them by running the following sql statement:
```
UPDATE USER 
```

**Comment by tryffel** [comment]
This will need a proper fix later on. I first thought it would be better to enforce all usernames to lowercase, but now I'm thinking it might make more sense to just allow logging in with case-insensitive username, but this would require some more work, e.g. ensuring that case-insensitive usernames are unique.

As a workaround for now, you can lowercase all usernames in the database with:
```sql
UPDATE users SET name=lower(name);

```

**Comment by tryffel** [comment]
Resolved with #10 .
